# input text file with like subject_id;gt_mesh_path;pred_mesh_path rows
in_file: /home/junjiez1/projects/corticalflow/resources/R.white_eval_list.csv

# index to start processing
start_idx: 0

# index to finish processing (-1 means the end of the in_files)
end_idx: -1

# evaluation batch size
batch_size: 1

# number of sampled points to run evaluation
num_sampled_points: 200000

# output directory to save the evaluation metrics
out_dir: /mnt/yaplab/data/junjiez/corticalflow_results/r_white/eval_results/

# hydra configurations and log files
hydra:
  run:
    dir: ${out_dir}
  output_subdir: null
